// One-Pager JSON Templates
import type { OnePagerLayout, OnePagerTemplateId } from "@/types/one-pager-layout";

export const ONE_PAGER_TEMPLATES: Record<Exclude<OnePagerTemplateId, 'auto'>, OnePagerLayout> = {
  // Template 1: Definition + Steps + Checklist
  "definition-steps": {
    version: 1,
    meta: {
      title: "{{title}}",
      audience: "{{audience}}",
      readTime: "~2 min read",
      tag: "Framework",
    },
    sections: [
      {
        id: "beat_1",
        beatNumber: 1,
        heading: "What Is This?",
        blocks: [
          {
            type: "card",
            title: "The Core Concept",
            bullets: [
              "Define the main idea clearly",
              "Explain why it matters now",
              "Show the transformation possible",
            ],
          },
        ],
      },
      {
        id: "beat_2",
        beatNumber: 2,
        heading: "The Steps",
        blocks: [
          {
            type: "steps",
            title: "Follow this process",
            steps: [
              "Start with your current state analysis",
              "Identify the gaps and opportunities",
              "Implement the core framework",
              "Measure and iterate",
            ],
          },
        ],
      },
      {
        id: "beat_3",
        beatNumber: 3,
        heading: "Quick Wins",
        blocks: [
          {
            type: "checklist",
            title: "Start with these today",
            items: [
              "Audit your current approach",
              "Pick one area to focus on",
              "Set a 7-day implementation goal",
              "Track your progress daily",
            ],
          },
          {
            type: "cta_buttons",
            primary: { label: "Get Started", actionText: "DM 'START'" },
            secondary: { label: "Save for Later", actionText: "Bookmark this" },
          },
        ],
      },
    ],
    footer: { text: "Generated by Content Factory" },
  },

  // Template 2: Problem → Fix → Example Table
  "problem-fix": {
    version: 1,
    meta: {
      title: "{{title}}",
      audience: "{{audience}}",
      readTime: "~3 min read",
      tag: "Problem/Solution",
    },
    sections: [
      {
        id: "beat_1",
        beatNumber: 1,
        heading: "The Problem",
        blocks: [
          {
            type: "warning",
            title: "Common Mistake",
            text: "Most people approach this the wrong way and waste time on ineffective strategies.",
          },
          {
            type: "card",
            title: "Why This Hurts",
            bullets: [
              "Wasted time and resources",
              "Missed opportunities",
              "Frustration and burnout",
            ],
          },
        ],
      },
      {
        id: "beat_2",
        beatNumber: 2,
        heading: "The Fix",
        blocks: [
          {
            type: "steps",
            title: "The solution process",
            steps: [
              "Recognize the pattern",
              "Apply the framework",
              "See immediate results",
            ],
          },
        ],
      },
      {
        id: "beat_3",
        beatNumber: 3,
        heading: "Before vs After",
        blocks: [
          {
            type: "table",
            title: "Comparison",
            columns: ["Metric", "Before", "After"],
            rows: [
              ["Time Spent", "10+ hours/week", "2 hours/week"],
              ["Results", "Random", "Predictable"],
              ["Confidence", "Low", "High"],
            ],
          },
          {
            type: "cta_buttons",
            primary: { label: "Get the Full Guide", actionText: "DM 'GUIDE'" },
          },
        ],
      },
    ],
    footer: { text: "Generated by Content Factory" },
  },

  // Template 3: Framework Cards + Scorecard
  "framework-scorecard": {
    version: 1,
    meta: {
      title: "{{title}}",
      audience: "{{audience}}",
      readTime: "~3 min read",
      tag: "Scorecard",
    },
    sections: [
      {
        id: "beat_1",
        beatNumber: 1,
        heading: "The Framework",
        blocks: [
          {
            type: "card",
            title: "Pillar 1: Foundation",
            bullets: ["Core principle A", "Core principle B"],
          },
          {
            type: "card",
            title: "Pillar 2: Execution",
            bullets: ["Implementation step 1", "Implementation step 2"],
          },
          {
            type: "card",
            title: "Pillar 3: Scale",
            bullets: ["Growth lever 1", "Growth lever 2"],
          },
        ],
      },
      {
        id: "beat_2",
        beatNumber: 2,
        heading: "Rate Yourself",
        blocks: [
          {
            type: "scorecard",
            title: "Your Current Score",
            rows: [
              { label: "Foundation", value: "Low / Med / High" },
              { label: "Execution", value: "Low / Med / High" },
              { label: "Scale", value: "Low / Med / High" },
            ],
          },
        ],
      },
      {
        id: "beat_3",
        beatNumber: 3,
        heading: "Next Steps",
        blocks: [
          {
            type: "checklist",
            items: [
              "Identify your weakest pillar",
              "Focus on 1 improvement this week",
              "Measure progress after 7 days",
            ],
          },
          {
            type: "cta_buttons",
            primary: { label: "Get Your Score", actionText: "DM 'SCORE'" },
          },
        ],
      },
    ],
    footer: { text: "Generated by Content Factory" },
  },

  // Template 4: How-to Playbook + Template Block
  "playbook": {
    version: 1,
    meta: {
      title: "{{title}}",
      audience: "{{audience}}",
      readTime: "~4 min read",
      tag: "Playbook",
    },
    sections: [
      {
        id: "beat_1",
        beatNumber: 1,
        heading: "The Strategy",
        blocks: [
          {
            type: "card",
            title: "Overview",
            bullets: [
              "What this playbook covers",
              "Expected outcomes",
              "Time investment needed",
            ],
          },
        ],
      },
      {
        id: "beat_2",
        beatNumber: 2,
        heading: "Step-by-Step",
        blocks: [
          {
            type: "steps",
            title: "The Process",
            steps: [
              "Gather your data and baseline metrics",
              "Identify your top 3 opportunities",
              "Create your action plan",
              "Execute and measure daily",
              "Adjust based on results",
            ],
          },
        ],
      },
      {
        id: "beat_3",
        beatNumber: 3,
        heading: "Copy This Template",
        blocks: [
          {
            type: "template",
            title: "Quick-Start Script",
            lines: [
              "[Your Hook] - The attention grabber",
              "[Problem] - What they're struggling with",
              "[Solution] - Your unique approach",
              "[Proof] - Why this works",
              "[CTA] - What to do next",
            ],
          },
          {
            type: "cta_buttons",
            primary: { label: "Get Full Playbook", actionText: "DM 'PLAYBOOK'" },
            secondary: { label: "Save Template", actionText: "Screenshot this" },
          },
        ],
      },
    ],
    footer: { text: "Generated by Content Factory" },
  },

  // Template 5: Audit Sheet + Checklist + Mini Chart
  "audit-sheet": {
    version: 1,
    meta: {
      title: "{{title}}",
      audience: "{{audience}}",
      readTime: "~5 min read",
      tag: "Audit",
    },
    sections: [
      {
        id: "beat_1",
        beatNumber: 1,
        heading: "Quick Audit",
        blocks: [
          {
            type: "checklist",
            title: "Check Your Current State",
            items: [
              "Do you have a clear value proposition?",
              "Is your messaging consistent?",
              "Are you tracking the right metrics?",
              "Do you have a follow-up system?",
            ],
          },
        ],
      },
      {
        id: "beat_2",
        beatNumber: 2,
        heading: "Performance Breakdown",
        blocks: [
          {
            type: "mini_bar_chart",
            title: "Typical Improvement Areas",
            data: [
              { name: "Messaging", value: 40 },
              { name: "Targeting", value: 65 },
              { name: "Follow-up", value: 30 },
              { name: "Conversion", value: 55 },
            ],
          },
          {
            type: "warning",
            title: "Watch Out",
            text: "Low follow-up scores are the #1 reason for lost deals. Fix this first.",
          },
        ],
      },
      {
        id: "beat_3",
        beatNumber: 3,
        heading: "Priority Actions",
        blocks: [
          {
            type: "scorecard",
            title: "Action Priority Matrix",
            rows: [
              { label: "Fix Messaging", value: "High Impact" },
              { label: "Improve Follow-up", value: "Quick Win" },
              { label: "Refine Targeting", value: "Medium Term" },
            ],
          },
          {
            type: "cta_buttons",
            primary: { label: "Get Full Audit", actionText: "DM 'AUDIT'" },
          },
        ],
      },
    ],
    footer: { text: "Generated by Content Factory" },
  },
};

export const TEMPLATE_OPTIONS: { id: OnePagerTemplateId; label: string; description: string }[] = [
  { id: 'auto', label: 'Auto (AI Chooses)', description: 'Let AI pick the best template' },
  { id: 'definition-steps', label: 'Definition + Steps', description: 'Explain concept, show steps, add checklist' },
  { id: 'problem-fix', label: 'Problem → Fix', description: 'Problem, solution, before/after comparison' },
  { id: 'framework-scorecard', label: 'Framework + Scorecard', description: 'Multi-pillar framework with self-rating' },
  { id: 'playbook', label: 'Playbook', description: 'How-to guide with copy-paste template' },
  { id: 'audit-sheet', label: 'Audit Sheet', description: 'Checklist audit with chart and priorities' },
];

// Helper to get template by ID
export function getTemplateById(id: OnePagerTemplateId): OnePagerLayout | null {
  if (id === 'auto') return null;
  return ONE_PAGER_TEMPLATES[id] || null;
}
