project_id = "dwhmvzooerxejustfqpt"

[functions.generate-tts]
verify_jwt = false

[functions.generate-design-prompt]
verify_jwt = false

[functions.generate-design-image]
verify_jwt = false

[functions.generate-onepager-layout]
verify_jwt = false

[functions.lead-webhook]
verify_jwt = false

[functions.publish-post]
verify_jwt = false